# Generated by Django 5.0.4 on 2024-06-01 03:02

import e_commers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footwear',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='000000', max_length=6, validators=[e_commers.models.validate_pincode]),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
