# Generated by Django 5.0.4 on 2024-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
