# Generated by Django 5.0.4 on 2024-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0006_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
