# Generated by Django 5.0.4 on 2024-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0007_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
