# Generated by Django 5.0.4 on 2024-06-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0009_order_footwear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='footwear',
        ),
    ]
