# Generated by Django 5.0.4 on 2024-06-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0011_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
