# Generated by Django 5.0.4 on 2024-06-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0012_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='footwear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commers.footwear'),
            preserve_default=False,
        ),
    ]
