# Generated by Django 5.0.4 on 2024-06-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0014_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='footwear',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
