# Generated by Django 5.0.4 on 2024-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0015_remove_order_footwear_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwear',
            name='slid_image',
            field=models.ImageField(default=1, upload_to='footwear_slideimages/'),
            preserve_default=False,
        ),
    ]
