# Generated by Django 5.0.4 on 2024-06-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0016_footwear_slid_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwear',
            name='slid_image',
        ),
    ]
