# Generated by Django 5.0.4 on 2024-06-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commers', '0017_remove_footwear_slid_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='footwear_sideerimages/')),
            ],
        ),
        migrations.AddField(
            model_name='footwear',
            name='sliderimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commers.sliderimage'),
            preserve_default=False,
        ),
    ]
